import _ from "lodash"

export const singersUS = [
    "Taylor Swift",
    "Ed Sheeran",
    "Beyoncé",
    "Ariana Grande",
    "Drake",
    "Rihanna",
    "Justin Bieber",
    "Katy Perry",
    "Bruno Mars",
    "Shawn Mendes",
    "The Weeknd",
    "Post Malone",
    "Billie Eilish",
    "Adele",
    "Dua Lipa",
    "Eminem",
    "Lady Gaga",
    "Sia",
    "Justin Timberlake",
    "Chris Brown",
    "Selena Gomez",
    "Sam Smith",
    "Miley Cyrus",
    "Lana Del Rey",
    "Halsey",
    "Zayn",
    "Nicki Minaj",
    "Khalid",
    "Coldplay",
    "Maroon 5",
    "John Legend",
    "Kendrick Lamar",
    "Imagine Dragons",
    "Camila Cabello",
    "Alicia Keys",
    "Twenty One Pilots",
    "Lorde",
    "Usher",
    "Shakira",
    "Avril Lavigne",
    "Rita Ora",
    "Gwen Stefani",
    "Demi Lovato",
    "Harry Styles",
    "Michael Jackson",
    "Whitney Houston",
    "Elton John",
    "Stevie Wonder",
    "Madonna",
    "Bob Dylan",
    "Prince",
    "David Bowie",
    "George Michael",
    "Freddie Mercury",
    "Frank Sinatra",
    "Janet Jackson",
    "Tina Turner",
    "Paul McCartney",
    "Sting",
    "Ray Charles",
    "Aretha Franklin",
    "Mariah Carey",
    "Celine Dion",
    "Cher",
    "Barbra Streisand",
    "Ella Fitzgerald",
    "Nat King Cole",
    "Louis Armstrong",
    "John Lennon",
    "Jim Morrison",
    "Johnny Cash",
    "Buddy Holly",
    "Elvis Presley",
    "Patsy Cline",
    "Frank Ocean",
    "Prince Royce",
    "Ricky Martin",
    "Romeo Santos",
    "Maluma",
    "Enrique Iglesias",
    "Jennifer Lopez",
    "Shawn Mendes",
    "Niall Horan",
    "Charlie Puth",
    "Jason Derulo",
    "Troye Sivan",
    "Adam Levine",
    "Zara Larsson",
    "Nick Jonas",
    "Liam Payne",
    "Joe Jonas",
    "Kevin Jonas",
    "Brendon Urie",
    "Dan Reynolds",
    "Brandon Flowers",
    "Thom Yorke",
    "Dave Grohl",
    "Anthony Kiedis",
    "Gerard Way",
    "Hayley Williams",
    "Brandon Boyd",
    "Matthew Bellamy",
    "Tom DeLonge",
    "Travis Barker",
    "Chris Martin",
    "Dave Matthews",
    "Ben Gibbard",
    "Gwen Stefani",
    "Kelly Clarkson",
    "Carrie Underwood",
    "Leona Lewis",
    "P!nk",
    "Alanis Morissette",
    "Sara Bareilles",
    "Norah Jones"
];

const sortedSingersUS: string[] = _.sortBy(singersUS);

const shuffledSingersUS: string[] = _.shuffle(sortedSingersUS);
export const randomSingerUS : String | undefined = _.sample(shuffledSingersUS);

console.log(randomSingerUS)

export const singersIR = [
    "Googoosh",
    "Mohsen Yeganeh",
    "Ebi",
    "Mansour",
    "Shadmehr Aghili",
    "Hayedeh",
    "Moein",
    "Dariush",
    "Farhad Mehrad",
    "Leila Forouhar",
    "Andy",
    "Hassan Shamaizadeh",
    "Martik",
    "Shahram Shabpareh",
    "Siavash Ghomayshi",
    "Helen",
    "Sattar",
    "Faramarz Aslani",
    "Hassan Sattar",
    "Ali Lohrasbi",
    "Ramesh",
    "Morteza Pashaei",
    "Sadegh",
    "Hoorosh Band",
    "Mohammad Esfahani",
    "Reza Sadeghi",
    "Shahram Solati",
    "Mohammad Reza Shajarian",
    "Gholamreza Sanatgar",
    "Shohreh",
    "Behnam Bani",
    "Hamed Homayoun",
    "Alireza Assar",
    "Siamak Abbasi",
    "Shakila",
    "Maziar Fallahi",
    "Afshin",
    "Arash",
    "Black Cats",
    "Ehsan Khajeh Amiri",
    "Sogand",
    "Mohammad Motamedi",
    "Mohammadreza Golzar",
    "Benyamin Bahadori",
    "Roozbeh Bemani",
    "Reza Yazdani",
    "Emad Talebzadeh",
    "Ramin Bibak",
    "Aref",
    "Homayoun Shajarian",
    "Siavash Shams",
    "Pouya Bayati",
    "Shahyad",
    "Majid Kharatha",
    "Shahab Mozaffari",
    "Mehdi Ahmadvand",
    "Sina Sarlak",
    "Amir Tataloo",
    "Omid Hajili",
    "Mehdi Yarrahi",
    "Sirvan Khosravi",
    "Mohsen Chavoshi",
    "Reza Ramyar",
    "Behzad Leito",
    "Ali Zand Vakili",
    "Nima Allameh",
    "Majid Eslahi",
    "Erfan",
    "Amirhossein Eftekhari",
    "Farzad Farzin",
    "Sina Shabankhani",
    "Hamid Asgari",
    "Naser Zeynali",
    "Shadmehr Aghili",
    "Shahram Nazeri",
    "Shahrzad Sepanlou",
    "Puzzle Band",
    "Pouya Saleki",
    "Soheil Jami",
    "Kamran Molaei",
    "Hamed Zamani",
    "Mahan Bahram Khan",
    "Majid Yahyaei",
    "Mohsen Ebrahimzadeh",
    "Hamed Baradaran",
    "Eddie Attar",
    "Mohammad Bibak",
    "Shayan Eshraghi",
    "Behnam Safavi",]


const shuffledSingersIR = _.shuffle(singersIR);

// انتخاب یک عنصر رندوم بدون تکرار
export const randomSingerIR = _.sample(shuffledSingersIR);
