import {Singers} from "../components/Singers";
import {SWRConfig} from "swr";
import verifyToken from "../utils/verifyToken";
import fetcherQuery from "../graphQl/query/fetcher/fetcherQuery";
import {SCHEMA_SEVERAL_ARTISTS} from "../graphQl/query/schema/getSeveralArtists";
import {NextApiRequest} from "next";

export default function singers({fallback} : {fallback : {}}) {
    return (
        <SWRConfig value={{fallback}}>
            <Singers/>
        </SWRConfig>
    )
}

export const getServerSideProps = async ({req} : {req : NextApiRequest}) => {

    const session =  verifyToken(req)

    const GET_SEVERAL_ARTISTS_FOR_PICKUP = await fetcherQuery(SCHEMA_SEVERAL_ARTISTS)

    return {
        props: {
            fallback: {
                "/api/getUserSession" : session ,
                "GET_SEVERAL_ARTISTS_FOR_PICKUP": GET_SEVERAL_ARTISTS_FOR_PICKUP
            }
        }
    }

}


export const SINGERS_NAME = [
    "Beyoncé",
    "Ed Sheeran",
    "Taylor Swift",
    "Adele",
    "Justin Bieber",
    "Rihanna",
    "Ariana Grande",
    "Bruno Mars",
    "Lady Gaga",
    "Drake",
    "Katy Perry",
    "The Weeknd",
    "Billie Eilish",
    "Shawn Mendes",
    "Dua Lipa",
    "John Legend",
    "Maroon5",
    "Sia",
    "Coldplay",
    "Sam Smith",
    "Post Malone",
    "Nicki Minaj",
    "Eminem",
    "Adele",
    "Elton John",
    "Whitney Houston",
    "Michael Jackson",
    "Bob Marley",
    "Madonna",
    "Queen",
    "Elvis Presley",
    "Celine Dion",
    "Frank Sinatra",
    "Prince",
    "David Bowie",
    "U2",
    "Nirvana",
    "Justin Timberlake",
    "Christina Aguilera",
    "Shakira",
    "Bruce Springsteen",
    "Bob Dylan",
    "Stevie Wonder",
    "Adele",
    "Tina Turner",
    "Aretha Franklin",
    "Whitney Houston",
    "George Michael",
    "Prince",
    "Elton John",
    "Jay-Z",
    "Beyoncé",
    "Bruno Mars",
    "Cardi B",
    "Rihanna",
    "Selena Gomez",
    "Khalid",
    "Justin Timberlake",
    "Lady Gaga",
    "John Legend",
    "Adele",
    "Sam Smith",
    "Demi Lovato",
    "Ariana Grande",
    "Taylor Swift",
    "Mariah Carey",
    "Alicia Keys",
    "Usher",
    "Britney Spears",
    "Coldplay",
    "John Lennon",
    "Freddie Mercury",
    "Whitney Houston",
    "Prince",
    "David Bowie",
    "Elton John",
    "Madonna",
    "Bob Marley",
    "Michael Jackson",
    "Billie Joe Armstrong",
    "Kurt Cobain",
    "Amy Winehouse",
    "Bob Dylan",
    "Aretha Franklin",
    "Tina Turner",
    "Frank Sinatra",
    "Johnny Cash",
    "Bruce Springsteen",
    "George Michael",
    "Eminem",
    "Shakira",
    "Christina Aguilera",
    "Freddie Mercury",
    "John Mayer",
    "Adele",
    "Stevie Nicks",
    "Thom Yorke",
    "Beyoncé",
    "Sting"
];


export const SINGER_NAME_PERSIAN = [
    "Mohammad Reza Shajarian",
    "Fereydoun Forooghi",
    "Mohsen Chavoshi",
    "Mohammad Alizadeh",
    "Iraj MirzaHosseini",
    "Mehrad Jam",
    "Hamid Hamidi",
    "Arman Mohammadi",
    "Shahram Shabpareh",
    "Ahangar",
    "Mehdi Yarrahi",
    "Hayedeh",
    "Dariush Eghbali",
    "Amin Rostami",
    "Ava-ye Boland",
    "Siavash Ghomayshi",
    "Behnam Bani",
    "Reza Yazdani",
    "Majid Kharatha",
    "Setar",
    "Sirvan Khosravi",
    "Gogosh",
    "Saman Jalili",
    "Mehdi Yarrahi",
    "Mohsen Ebrahimzadeh",
    "Ahmad Saeedi",
    "Benjamin Bahadori",
    "Mohsen Namjoo",
    "Hamed Hamidian",
    "Atrin",
    "Amin Habibi",
    "Zaniar Khosravi",
    "Mazyar Fallahi",
    "Mohammad Abbasi",
    "Reza Sadeghi",
    "Ehsan Khaje Amiri",
    "Mohammad Motamedi",
    "Shahab Mozaffari",
    "Ali Abdolmaleki",
    "Bijan Bijani",
    "Saeed ShayeSteh",
    "Shadmehr Aghili",
    "Ramin BeyanDari",
    "Amir Tataloo",
    "Asef Aria",
    "Hamid Soltani",
    "Mohammad Esfahani",
    "Kianoosh",
    "Shahre",
    "Omid Hajili",
    "Mohsen Yeganeh",
    "Ali Lohrasbi",
    "Shahram Solati",
    "Ali Zand Vakili",
    "Ebi",
    "Moein",
    "Leila Forouhar",
    "Homeyra",
    "Sattar",
    "Shohreh Solati",
    "Sasy Mankan",
    "Reza Sadeghi",
    "Babak Jahanbakhsh",
    "Mohsen Ebrahimzadeh",
    "Andy",
    "Mansour",
    "Black Cats",
    "Amirhossein Eftekhari",
    "Farhad Mehrad",
    "Shahab Tiam",
    "Hichkas",
    "25Band",
    "Puzzle Band",
    "Behzad Leito",
    "Yas",
    "Kourosh Yaghmaei",
    "Alireza Assar",
    "Shahrzad Sepanlou",
    "Parisa",
    "Ehsan Khaje Amiri",
    "Pouya Bayati",
    "Morteza Pashaei",
    "Reza Bahram",
    "Ramin Bibak",
    "Kamran & Hooman",
    "Farzin",
    "Afshin",
    "Shervin",
    "Tohi",
    "Erfan",
    "Ali Ashabi",
    "Ali Abdolmaleki",
    "Ali Yasini",
    "Amin Fayyaz",
    "Arash",
    "Baran",
    "Hamed Homayoun",
    "Hasan Shamaizadeh",
    "Hossein Tohi",
    "Iman Sani",
    "Kamran Molaei",
    "Macan Band",
    "Mohammad Alizadeh",
    "Mohsen Chavoshi",
    "Omid Soltani",
    "Ramin Djawadi",
    "Roozbeh Nematollahi",
    "Saeed Shayesteh",
    "Sirvan Khosravi",
    "Sohrab Pakzad"
];
