name: Deploy Next.js App

on:
  push:
    branches:
      - main # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }} # Create a personal access token with repo scope in GitHub and add it as a secret in your repository settings
          BRANCH: gh-pages # Change this to your desired branch name for deployment
          FOLDER: build # Change this to the folder where Next.js builds your app
